name: Release to github packages

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build and push docker image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: docker.io/joshcarp/gh-pages-internal
          tag_with_ref: true
          tag_with_latest: true
          add_git_labels: true